---
- name: Include os specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "default.yml"

- name: Install required packages.
  package:
    name:
      - git
      - python3-virtualenv

- name: clone librenms agent setup.
  git:
    repo: "{{ librenms_agent_agent_repo }}"
    dest: "{{ librenms_agent_agent_dir }}"
    version: "{{ librenms_agent_agent_branch }}"
  tags:
    - librenms-agent-clone

- name: setup snmp.
  include_tasks: setup_snmp.yml
  tags:
    - librenms-agent-snmp

- name: setup check_mk.
  include_tasks: setup_check_mk.yml
  tags:
    - librenms-agent-check_mk


- name: Deploy systemd service file.
  template:
    src: "templates/etc/systemd/system/snmpd.service.j2"
    dest: "/etc/systemd/system/snmpd.service"
    mode: 0640
    owner: "{{ librenms_agent_snmp_owner }}"
    group: "{{ librenms_agent_snmp_group }}"
  notify: restart snmpd
  tags:
    - librenms-service

- name: Reload snmpd.
  systemd:
    name: snmpd
    state: started
    enabled: yes
    daemon_reload: yes
  tags:
    - librenms-service
