- name: "snmp : apache : install required python modules."
  package:
    name:
      - python-urlgrabber
      - python-pycurl

- name: "snmp : apache :Ensure cache directory is present."
  file:
    path: /var/cache/librenms
    state: directory
    owner: Debian-snmp