- name: "checkmk : copy check_mk agent bin."
  copy:
    src: "{{ librenms_agent_agent_dir }}/check_mk_agent"
    dest: "/usr/bin/check_mk_agent"
    remote_src: yes
    mode: 0755
  notify: restart check_mk

- name: "checkmk : copy check_mk service files."
  copy:
    src: "{{ librenms_agent_agent_dir }}/{{ item }}"
    dest: "/etc/systemd/system"
    remote_src: yes
    mode: 0644
  with_items:
    - "check_mk@.service"
    - "check_mk.socket"
  notify: restart check_mk

- name: "checkmk : create check_mk directories."
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ librenms_agent_check_mk_local_dir }}"
    - "{{ librenms_agent_check_mk_plugins_dir }}"
    - "/var/cache/librenms"
  notify: restart check_mk.

- name: "checkmk : get files in {{ librenms_agent_check_mk_local_dir }}."
  find:
    paths: "{{ librenms_agent_check_mk_local_dir }}"
  register: check_mk_contents

- name: "checkmk : delete not managed files from: {{ librenms_agent_check_mk_local_dir }}."
  file:
    path: "{{ librenms_agent_check_mk_local_dir }}/{{ item }}"
    state: absent
  with_items: "{{ check_mk_contents.files }}"
  when: librenms_agent_check_mk_extensions | selectattr('script','search', (item.path | basename | splitext)[0] ) | list | count == 0

- name: "checkmk : copy check_mk extensions."
  copy:
    src: "{{ librenms_agent_agent_dir }}/agent-local/{{ item.script }}"
    dest: "{{ librenms_agent_check_mk_local_dir }}"
    mode: 0755
    remote_src: yes
  with_items: "{{ librenms_agent_check_mk_extensions }}"
  notify: restart check_mk

- name: "checkmk : include nginx setup when nginx is in the extensions."
  include_tasks: setup_check_mk_nginx.yml
  when: librenms_agent_check_mk_extensions | selectattr('script','equalto','nginx') | list | count > 0

- name: "checkmk : enable check_mk service."
  systemd:
    name: check_mk.socket
    enabled: yes
    daemon_reload: yes
  notify: restart check_mk