---
- name: "Checkmk : copy check_mk agent bin."
  ansible.builtin.copy:
    src: "{{ librenms_agent_agent_dir }}/check_mk_agent"
    dest: "/usr/bin/check_mk_agent"
    remote_src: true
    mode: "0750"
  notify: restart check_mk

- name: "Checkmk : copy check_mk service file."
  ansible.builtin.copy:
    src: "{{ librenms_agent_agent_dir }}/check_mk@.service"
    dest: "/etc/systemd/system"
    remote_src: true
    mode: "0644"
    owner: "{{ librenms_agent_snmp_owner }}"
    group: "{{ librenms_agent_snmp_group }}"
  notify: restart check_mk

- name: "Checkmk : deploy check_mk socket file."
  ansible.builtin.template:
    src: "templates/etc/systemd/system/check_mk.socket.j2"
    dest: "/etc/systemd/system/check_mk.socket"
    mode: "0640"
    owner: "{{ librenms_agent_snmp_owner }}"
    group: "{{ librenms_agent_snmp_group }}"
  notify: restart check_mk

- name: "Checkmk : create check_mk directories."
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ librenms_agent_snmp_owner }}"
    group: "{{ librenms_agent_snmp_group }}"
  with_items:
    - "{{ librenms_agent_check_mk_local_dir }}"
    - "{{ librenms_agent_check_mk_plugins_dir }}"
    - "/var/cache/librenms"
  notify: restart check_mk

- name: "Checkmk : get files in {{ librenms_agent_check_mk_local_dir }}."
  ansible.builtin.find:
    paths: "{{ librenms_agent_check_mk_local_dir }}"
  register: check_mk_contents

- name: "Checkmk : delete not managed files from: {{ librenms_agent_check_mk_local_dir }}."
  ansible.builtin.file:
    path: "{{ librenms_agent_check_mk_local_dir }}/{{ item }}"
    state: absent
  with_items: "{{ check_mk_contents.files }}"
  when: >-
    librenms_agent_check_mk_extensions |
    selectattr('script','search', (item.path | basename | splitext)[0] ) | list | count == 0

- name: "Checkmk : copy check_mk extensions."
  ansible.builtin.copy:
    src: "{{ librenms_agent_agent_dir }}/agent-local/{{ item.script }}"
    dest: "{{ librenms_agent_check_mk_local_dir }}"
    mode: "0750"
    owner: "{{ librenms_agent_snmp_owner }}"
    group: "{{ librenms_agent_snmp_group }}"
    remote_src: true
  with_items: "{{ librenms_agent_check_mk_extensions }}"
  notify: restart check_mk

- name: "Checkmk : include nginx setup when nginx is in the extensions."
  ansible.builtin.include_tasks: setup_check_mk_nginx.yml
  when: librenms_agent_check_mk_extensions | selectattr('script','equalto','nginx') | list | count > 0

- name: "Checkmk : enable check_mk service."
  ansible.builtin.systemd:
    name: check_mk.socket
    enabled: true
    daemon_reload: true
  notify: restart check_mk
