- name: install required python modules.
  package:
    name:
      - python-openssl

- name: Deploy certificate.
  template:
    src: templates/certificate.json.j2
    dest: "/etc/snmp/certificate.json"
    mode: uog+x
