---
- name: "SNMP :  mysql : configure mysql.cnf."
  ansible.builtin.template:
    src: mysql.cnf.j2
    dest: "{{ librenms_agent_snmp_snmpd_extends_dir }}/mysql.cnf"
    mode: "0640"
    owner: "{{ librenms_agent_snmp_owner }}"
    group: "{{ librenms_agent_snmp_group }}"
  notify: restart snmpd
