- name: "snmp : apache : install required os packages."
  apt:
    name: "{{ librenms_agent_snmp_apache_os_packages }}"

- name: "snmp : apache : install required python modules."
  pip:
    name: "{{ librenms_agent_snmp_apache_pip_packages }}"
