---
- name: Set state fact
  ansible.builtin.set_fact:
    osupdates_unpriv_state: >-
      {{ librenms_agent_snmp_extensions |
      selectattr('executable', 'defined') |
      selectattr('executable', 'equalto', '/usr/local/bin/osupdates-unpriv-gather.sh') |
      map(attribute='state') | list | first | default('present') }}

- name: "SNMP :  unpriv osupdates : Install/Uninstall package dependencies."
  ansible.builtin.package:
    name:
      - libsnmp-dev
    state: "{{ osupdates_unpriv_state }}"
  tags:
    - packages

- name: Add unpriv os update utilities
  when: osupdates_unpriv_state == 'present'
  block:
    - name: "SNMP :  unpriv osupdates : scripts."
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "/usr/local/bin/"
        remote_src: yes
        force: "{{ item.copy_force | default('yes') }}"
        mode: 0750
        owner: "{{ librenms_agent_snmp_owner }}"
        group: "{{ librenms_agent_snmp_group }}"
      with_items:
        - src: "{{ librenms_agent_agent_dir_snmp }}/unpriv/osupdates/osupdates-unpriv-gather.sh"
        - src: "{{ librenms_agent_agent_dir_snmp }}/unpriv/osupdates/osupdates-unpriv-generate.sh"

    - name: "SNMP :  unpriv osupdates : timer and service."
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "/etc/systemd/system/"
        remote_src: yes
        force: "{{ item.copy_force | default('yes') }}"
        mode: 0640
        owner: "root"
        group: "root"
      with_items:
        - src: "{{ librenms_agent_agent_dir_snmp }}/unpriv/osupdates/librenms-osupdates-generate.timer"
        - src: "{{ librenms_agent_agent_dir_snmp }}/unpriv/osupdates/librenms-osupdates-generate.service"

    - name: "SNMP :  unpriv osupdates : enable timer."
      ansible.builtin.systemd_service:
        name: librenms-osupdates-generate.timer
        enabled: true
        state: started
      register: timer_result

    - name: "SNMP :  unpriv osupdates : run generate once."
      ansible.builtin.command: "/usr/local/bin/osupdates-unpriv-generate.sh"
      changed_when: true
      when: timer_result.changed

- name: "SNMP :  unpriv osupdates : Remove unpriv os update utilities"
  when: osupdates_unpriv_state == 'absent'
  block:
    - name: "SNMP :  unpriv osupdates : check if timer exists."
      ansible.builtin.stat:
        path: /etc/systemd/system/librenms-osupdates-generate.timer
      register: timer_result

    - name: "SNMP :  unpriv osupdates : disable timer."
      ansible.builtin.systemd_service:
        name: librenms-osupdates-generate.timer
        enabled: false
        state: stopped
      when: timer_result.stat.exists

    - name: "SNMP :  unpriv osupdates : remove files."
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /usr/local/bin/osupdates-unpriv-gather.sh
        - /usr/local/bin/osupdates-unpriv-generate.sh
        - /etc/systemd/system/librenms-osupdates-generate.timer
        - /etc/systemd/system/librenms-osupdates-generate.service
