- name: "snmp : fail2ban : Install required packages."
  package:
    name:
      - libjson-perl

- name: "snmp : fail2ban : setup fail2ban cronjob."
  cron:
    name: "Update snmp extend fail2ban"
    minute: "*/3"
    job: /etc/snmp/snmpd.d/fail2ban -u