- name: "snmp : certificate : install required python modules."
  package:
    name:
      - python-openssl

- name: "snmp : certificate : deploy certificate."
  template:
    src: templates/certificate.json.j2
    dest: "/etc/snmp/certificate.json"
    mode: uog+x
