---
- name: "SNMP :  certificate : install required python modules."
  ansible.builtin.package:
    name:
      - python3-openssl

- name: "SNMP :  certificate : deploy certificate."
  ansible.builtin.template:
    src: templates/certificate.json.j2
    dest: "/etc/snmp/certificate.json"
    mode: 0750
    owner: "{{ librenms_agent_snmp_owner }}"
    group: "{{ librenms_agent_snmp_group }}"
