---
- name: Restart snmpd
  ansible.builtin.service:
    name: "{{ librenms_agent_service_name }}"
    state: restarted

- name: Restart check_mk
  ansible.builtin.systemd:
    name: check_mk.socket
    state: restarted

- name: Restart cron
  ansible.builtin.service:
    name: cron
    state: restarted
