---
librenms_agent_snmp_apache_os_packages:
  - libcurl4-openssl-dev
  - libssl-dev

librenms_agent_snmp_apache_pip_packages:
  - urlgrabber
  - pycurl

librenms_agent_snmp_docker_pip_packages:
  - python-dateutil
